name: Main Build
on:
  push:
    branches: 
    - main
permissions: write-all
jobs:
  copydev:
    name: Copy main branch to published branch
    runs-on: ubuntu-latest
    steps:
    - name: checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        path: branchmain
    - name: copy main
      run: |
        mkdir -p temp
        cp -r -v branchmain/* temp/
      shell: bash
    - name: echo & ls
      run: |
        echo "cd temp"
        cd temp
        echo "ls"
        echo "*****"
        ls
        echo "***************"
        echo "cd temp/docs"
        cd docs
        echo "ls"
        echo "*****"
        ls
    - name: git-publish-subdir
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: published
        FOLDER: temp
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
